export const diets = [
  { name: "Vegan" },
  { name: "Vegetarian" },
  { name: "Pescatarian" },
  { name: "Keto" },
  { name: "Paleo" },
  { name: "Low Carb" },
  { name: "Gluten-Free" },
  { name: "Dairy-Free" },
  { name: "Whole30" },
  { name: "Mediterranean" },
  { name: "Atkins" },
  { name: "South Beach" },
  { name: "Zone" },
  { name: "DASH" },
  { name: "Flexitarian" },
  { name: "Plant-Based" },
  { name: "Intermittent Fasting" },
  { name: "Raw Food" },
  { name: "Low Fat" },
  { name: "High Protein" },
  { name: "Blood Type" },
  { name: "Anti-Inflammatory" },
  { name: "Carnivore" },
  { name: "Macrobiotic" },
  { name: "FODMAP" },
];

export const intolerances = [
  { name: "Gluten" },
  { name: "Lactose" },
  { name: "Peanuts" },
  { name: "Tree Nuts" },
  { name: "Eggs" },
  { name: "Fish" },
  { name: "Shellfish" },
  { name: "Soy" },
  { name: "Wheat" },
  { name: "Sesame" },
  { name: "Sulfites" },
  { name: "Mustard" },
  { name: "Celery" },
  { name: "Mollusks" },
  { name: "Corn" },
  { name: "Legumes" },
  { name: "Yeast" },
  { name: "Citrus" },
  { name: "Red Meat" },
  { name: "Poultry" },
  { name: "Fruits" },
  { name: "Vegetables" },
  { name: "Dairy" },
  { name: "Spices" },
  { name: "Herbs" },
  { name: "Alcohol" },
  { name: "Caffeine" },
  { name: "Nightshades" },
  { name: "Histamines" },
  { name: "FODMAPs" },
];
