export const diets = [
  { name: "Vegan" },
  { name: "Vegetarian" },
  { name: "Pescatarian" },
  { name: "Keto" },
  { name: "Paleo" },
  { name: "Low Carb" },
  { name: "Gluten-Free" },
  { name: "Dairy-Free" },
  { name: "Whole30" },
  { name: "Mediterranean" },
  { name: "Atkins" },
  { name: "South Beach" },
  { name: "Zone" },
  { name: "DASH" },
  { name: "Flexitarian" },
  { name: "Plant-Based" },
  { name: "Intermittent Fasting" },
  { name: "Raw Food" },
  { name: "Low Fat" },
  { name: "High Protein" },
  { name: "Blood Type" },
  { name: "Anti-Inflammatory" },
  { name: "Carnivore" },
  { name: "Macrobiotic" },
  { name: "FODMAP" },
];
