const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Ingredient = require("./models/Ingredient");

dotenv.config();

const ingredients = [
  { name: "Almond Milk" },
  { name: "Coconut Milk" },
  { name: "Evaporated Milk" },
  { name: "Condensed Milk" },
  { name: "Heavy Cream" },
  { name: "Half and Half" },
  { name: "Parmesan Cheese" },
  { name: "Mozzarella Cheese" },
  { name: "Feta Cheese" },
  { name: "Goat Cheese" },
  { name: "Ricotta Cheese" },
  { name: "Blue Cheese" },
  { name: "Sour Cream" },
  { name: "Buttermilk" },
  { name: "Cottage Cheese" },
  { name: "Mayonnaise" },
  { name: "Ketchup" },
  { name: "Mustard" },
  { name: "Hot Sauce" },
  { name: "BBQ Sauce" },
  { name: "Worcestershire Sauce" },
  { name: "Tabasco Sauce" },
  { name: "Sriracha Sauce" },
  { name: "Hoisin Sauce" },
  { name: "Fish Sauce" },
  { name: "Oyster Sauce" },
  { name: "Pesto" },
  { name: "Tahini" },
  { name: "Peanut Butter" },
  { name: "Almond Butter" },
  { name: "Jam" },
  { name: "Jelly" },
  { name: "Cranberries" },
  { name: "Dates" },
  { name: "Raisins" },
  { name: "Dried Apricots" },
  { name: "Dried Figs" },
  { name: "Dried Mango" },
  { name: "Dried Pineapple" },
  { name: "Dried Tomatoes" },
  { name: "Olives" },
  { name: "Capers" },
  { name: "Pickles" },
  { name: "Sauerkraut" },
  { name: "Kimchi" },
  { name: "Artichoke Hearts" },
  { name: "Sun-Dried Tomatoes" },
  { name: "Anchovies" },
  { name: "Sardines" },
  { name: "Smoked Salmon" },
  { name: "Tuna" },
  { name: "Mackerel" },
  { name: "Canned Corn" },
  { name: "Canned Peas" },
  { name: "Canned Beans" },
  { name: "Canned Chickpeas" },
  { name: "Canned Lentils" },
  { name: "Canned Tomatoes" },
  { name: "Canned Coconut Milk" },
  { name: "Canned Pineapple" },
  { name: "Canned Peaches" },
  { name: "Canned Pears" },
  { name: "Canned Pumpkin" },
  { name: "Canned Sweet Potatoes" },
  { name: "Canned Yams" },
  { name: "Canned Artichokes" },
  { name: "Canned Hearts of Palm" },
  { name: "Canned Water Chestnuts" },
  { name: "Canned Bamboo Shoots" },
  { name: "Canned Mushrooms" },
  { name: "Canned Asparagus" },
  { name: "Canned Green Beans" },
  { name: "Canned Carrots" },
  { name: "Canned Beets" },
  { name: "Canned Spinach" },
  { name: "Canned Kale" },
  { name: "Canned Collard Greens" },
  { name: "Canned Mustard Greens" },
  { name: "Canned Swiss Chard" },
  { name: "Canned Black Beans" },
  { name: "Canned Kidney Beans" },
  { name: "Canned Pinto Beans" },
  { name: "Canned Navy Beans" },
  { name: "Canned Butter Beans" },
  { name: "Canned Cannellini Beans" },
  { name: "Canned Great Northern Beans" },
  { name: "Canned Lima Beans" },
  { name: "Canned Fava Beans" },
  { name: "Canned Black-Eyed Peas" },
  { name: "Canned Pigeon Peas" },
  { name: "Canned Mung Beans" },
  { name: "Canned Adzuki Beans" },
  { name: "Canned Soybeans" },
  { name: "Canned Edamame" },
  { name: "Canned Jackfruit" },
  { name: "Canned Lychee" },
  { name: "Canned Mangosteen" },
  { name: "Canned Rambutan" },
  { name: "Canned Longan" },
  { name: "Canned Durian" },
  { name: "Canned Dragon Fruit" },
  { name: "Canned Guava" },
  { name: "Canned Passion Fruit" },
  { name: "Canned Starfruit" },
  { name: "Canned Persimmon" },
  { name: "Canned Quince" },
];

mongoose
  .connect(process.env.MONGO_URI, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(() => {
    console.log("Connected to MongoDB");
    return Ingredient.insertMany(ingredients);
  })
  .then(() => {
    console.log("Ingredients inserted successfully");
    mongoose.connection.close();
  })
  .catch((error) => {
    console.error("Error inserting ingredients:", error);
    mongoose.connection.close();
  });
